services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT}
      HOST: ${HOST}
      SWAGGER_JSON: ${SWAGGER_JSON}
    ports:
      - ${SERVER_PORT}:8080
